services:
  series_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: series_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./latest_episode.txt:/app/latest_episode.txt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
