services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    volumes:
      - .:/app
    environment:
      - TELEGRAM_BOT_TOKEN=${BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${CHAT_ID}
    restart: always
  